// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/mconfigcenter/example/biz"
	"github.com/995933447/mconfigcenter/example/bizserver/handler"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(biz.EasymicroGRPCPbServiceNameBiz, "GetVipMaxLevelLimit", handler.BizHandler.GetVipMaxLevelLimit, func() *biz.GetVipMaxLevelLimitReq {
		return &biz.GetVipMaxLevelLimitReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
