// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/mconfigcenter/example/biz"
	"github.com/995933447/mconfigcenter/example/bizserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	biz.EasymicroGRPCPbServiceNameBiz,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	biz.RegisterBizServer(server, handler.BizHandler)
	return nil
}
