// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: configcenter.proto

package configcenter

import (
	_ "github.com/995933447/easymicro/pb"
	common "github.com/995933447/mconfigcenter/common"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil                  ErrCode = 0
	ErrCode_ErrCodeParamInvalid         ErrCode = 1001
	ErrCode_ErrCodeConfigSchemaNotFound ErrCode = 1002
	ErrCode_ErrCodeValidateSchemaFailed ErrCode = 1003
	ErrCode_ErrCodeConfigNotFound       ErrCode = 1004
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		1001: "ErrCodeParamInvalid",
		1002: "ErrCodeConfigSchemaNotFound",
		1003: "ErrCodeValidateSchemaFailed",
		1004: "ErrCodeConfigNotFound",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":                  0,
		"ErrCodeParamInvalid":         1001,
		"ErrCodeConfigSchemaNotFound": 1002,
		"ErrCodeValidateSchemaFailed": 1003,
		"ErrCodeConfigNotFound":       1004,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_configcenter_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_configcenter_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{0}
}

type SetKeyValueReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Config                *common.KVConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ShouldNotifyListeners bool                   `protobuf:"varint,2,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,3,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetKeyValueReq) Reset() {
	*x = SetKeyValueReq{}
	mi := &file_configcenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueReq) ProtoMessage() {}

func (x *SetKeyValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueReq.ProtoReflect.Descriptor instead.
func (*SetKeyValueReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{0}
}

func (x *SetKeyValueReq) GetConfig() *common.KVConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SetKeyValueReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *SetKeyValueReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type SetKeyValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyValueResp) Reset() {
	*x = SetKeyValueResp{}
	mi := &file_configcenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueResp) ProtoMessage() {}

func (x *SetKeyValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueResp.ProtoReflect.Descriptor instead.
func (*SetKeyValueResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{1}
}

type GetKeyValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueReq) Reset() {
	*x = GetKeyValueReq{}
	mi := &file_configcenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueReq) ProtoMessage() {}

func (x *GetKeyValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueReq.ProtoReflect.Descriptor instead.
func (*GetKeyValueReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKeyValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *common.KVConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueResp) Reset() {
	*x = GetKeyValueResp{}
	mi := &file_configcenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueResp) ProtoMessage() {}

func (x *GetKeyValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueResp.ProtoReflect.Descriptor instead.
func (*GetKeyValueResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyValueResp) GetConfig() *common.KVConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetKeyValueResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddConfigsReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配置集合的名称
	Values                [][]byte               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`                                                               // 具体配置列表
	ShouldNotifyListeners bool                   `protobuf:"varint,3,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,4,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddConfigsReq) Reset() {
	*x = AddConfigsReq{}
	mi := &file_configcenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfigsReq) ProtoMessage() {}

func (x *AddConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfigsReq.ProtoReflect.Descriptor instead.
func (*AddConfigsReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{4}
}

func (x *AddConfigsReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *AddConfigsReq) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *AddConfigsReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *AddConfigsReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type AddConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigIds     []string               `protobuf:"bytes,1,rep,name=config_ids,json=configIds,proto3" json:"config_ids,omitempty"` // 新增的配置id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConfigsResp) Reset() {
	*x = AddConfigsResp{}
	mi := &file_configcenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfigsResp) ProtoMessage() {}

func (x *AddConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfigsResp.ProtoReflect.Descriptor instead.
func (*AddConfigsResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{5}
}

func (x *AddConfigsResp) GetConfigIds() []string {
	if x != nil {
		return x.ConfigIds
	}
	return nil
}

type UpdateConfigsReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配置集合的名称
	Ids                   []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`                                                                     // 配置id
	Value                 []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                                                 // 具体配置
	ShouldNotifyListeners bool                   `protobuf:"varint,4,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,5,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateConfigsReq) Reset() {
	*x = UpdateConfigsReq{}
	mi := &file_configcenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigsReq) ProtoMessage() {}

func (x *UpdateConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigsReq.ProtoReflect.Descriptor instead.
func (*UpdateConfigsReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConfigsReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *UpdateConfigsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *UpdateConfigsReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateConfigsReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *UpdateConfigsReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type UpdateConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigsResp) Reset() {
	*x = UpdateConfigsResp{}
	mi := &file_configcenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigsResp) ProtoMessage() {}

func (x *UpdateConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigsResp.ProtoReflect.Descriptor instead.
func (*UpdateConfigsResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{7}
}

type AddConfigReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配置集合的名称
	Value                 []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                                                 // 具体配置
	ShouldNotifyListeners bool                   `protobuf:"varint,3,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,4,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddConfigReq) Reset() {
	*x = AddConfigReq{}
	mi := &file_configcenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfigReq) ProtoMessage() {}

func (x *AddConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfigReq.ProtoReflect.Descriptor instead.
func (*AddConfigReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{8}
}

func (x *AddConfigReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *AddConfigReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AddConfigReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *AddConfigReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type AddConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // 新增的配置id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConfigResp) Reset() {
	*x = AddConfigResp{}
	mi := &file_configcenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfigResp) ProtoMessage() {}

func (x *AddConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfigResp.ProtoReflect.Descriptor instead.
func (*AddConfigResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{9}
}

func (x *AddConfigResp) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type UpdateConfigReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配置集合的名称
	Id                    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                       // 配置id
	Value                 []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                                                 // 具体配置
	ShouldNotifyListeners bool                   `protobuf:"varint,4,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,5,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateConfigReq) Reset() {
	*x = UpdateConfigReq{}
	mi := &file_configcenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigReq) ProtoMessage() {}

func (x *UpdateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigReq.ProtoReflect.Descriptor instead.
func (*UpdateConfigReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateConfigReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *UpdateConfigReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateConfigReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateConfigReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *UpdateConfigReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type UpdateConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResp) Reset() {
	*x = UpdateConfigResp{}
	mi := &file_configcenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResp) ProtoMessage() {}

func (x *UpdateConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResp.ProtoReflect.Descriptor instead.
func (*UpdateConfigResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{11}
}

type DeleteConfigReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配合集合的名称
	Id                    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                       // 配置id
	ShouldNotifyListeners bool                   `protobuf:"varint,3,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,4,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeleteConfigReq) Reset() {
	*x = DeleteConfigReq{}
	mi := &file_configcenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigReq) ProtoMessage() {}

func (x *DeleteConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigReq.ProtoReflect.Descriptor instead.
func (*DeleteConfigReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteConfigReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *DeleteConfigReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteConfigReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *DeleteConfigReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type DeleteConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResp) Reset() {
	*x = DeleteConfigResp{}
	mi := &file_configcenter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResp) ProtoMessage() {}

func (x *DeleteConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResp.ProtoReflect.Descriptor instead.
func (*DeleteConfigResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{13}
}

type DeleteConfigsReq struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollName              string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                                           // 配合集合的名称
	Ids                   []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`                                                                     // 配置id
	ShouldNotifyListeners bool                   `protobuf:"varint,3,opt,name=should_notify_listeners,json=shouldNotifyListeners,proto3" json:"should_notify_listeners,omitempty"` // 是否立刻通知配置监听者
	ListenerGroup         string                 `protobuf:"bytes,4,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`                            // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeleteConfigsReq) Reset() {
	*x = DeleteConfigsReq{}
	mi := &file_configcenter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigsReq) ProtoMessage() {}

func (x *DeleteConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigsReq.ProtoReflect.Descriptor instead.
func (*DeleteConfigsReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteConfigsReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *DeleteConfigsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteConfigsReq) GetShouldNotifyListeners() bool {
	if x != nil {
		return x.ShouldNotifyListeners
	}
	return false
}

func (x *DeleteConfigsReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

type DeleteConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigsResp) Reset() {
	*x = DeleteConfigsResp{}
	mi := &file_configcenter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigsResp) ProtoMessage() {}

func (x *DeleteConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigsResp.ProtoReflect.Descriptor instead.
func (*DeleteConfigsResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{15}
}

type ListConfigReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CollName      string                    `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"` // 集合名称
	Offset        uint32                    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                    // 位移
	Limit         uint32                    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 条数
	Sorts         []*ListConfigReq_Sort     `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`                       // 排序
	Filter        []byte                    `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`                     // 过滤
	Selectors     []*ListConfigReq_Selector `protobuf:"bytes,6,rep,name=selectors,proto3" json:"selectors,omitempty"`               // 字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq) Reset() {
	*x = ListConfigReq{}
	mi := &file_configcenter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq) ProtoMessage() {}

func (x *ListConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq.ProtoReflect.Descriptor instead.
func (*ListConfigReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{16}
}

func (x *ListConfigReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *ListConfigReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConfigReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConfigReq) GetSorts() []*ListConfigReq_Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListConfigReq) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListConfigReq) GetSelectors() []*ListConfigReq_Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type ListConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          [][]byte               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigResp) Reset() {
	*x = ListConfigResp{}
	mi := &file_configcenter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigResp) ProtoMessage() {}

func (x *ListConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigResp.ProtoReflect.Descriptor instead.
func (*ListConfigResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{17}
}

func (x *ListConfigResp) GetList() [][]byte {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListConfigResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NotifyListenersReloadConfigReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ListenerGroup   string                 `protobuf:"bytes,1,opt,name=listener_group,json=listenerGroup,proto3" json:"listener_group,omitempty"`          // 需要通知的监听者组别,由配置发布方根据业务自定义,非必需
	CollNames       []string               `protobuf:"bytes,2,rep,name=coll_names,json=collNames,proto3" json:"coll_names,omitempty"`                      // 集合名称
	ShouldReloadAll bool                   `protobuf:"varint,3,opt,name=should_reload_all,json=shouldReloadAll,proto3" json:"should_reload_all,omitempty"` // 是否需要全量同步
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotifyListenersReloadConfigReq) Reset() {
	*x = NotifyListenersReloadConfigReq{}
	mi := &file_configcenter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyListenersReloadConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyListenersReloadConfigReq) ProtoMessage() {}

func (x *NotifyListenersReloadConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyListenersReloadConfigReq.ProtoReflect.Descriptor instead.
func (*NotifyListenersReloadConfigReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{18}
}

func (x *NotifyListenersReloadConfigReq) GetListenerGroup() string {
	if x != nil {
		return x.ListenerGroup
	}
	return ""
}

func (x *NotifyListenersReloadConfigReq) GetCollNames() []string {
	if x != nil {
		return x.CollNames
	}
	return nil
}

func (x *NotifyListenersReloadConfigReq) GetShouldReloadAll() bool {
	if x != nil {
		return x.ShouldReloadAll
	}
	return false
}

type NotifyListenersReloadConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyListenersReloadConfigResp) Reset() {
	*x = NotifyListenersReloadConfigResp{}
	mi := &file_configcenter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyListenersReloadConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyListenersReloadConfigResp) ProtoMessage() {}

func (x *NotifyListenersReloadConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyListenersReloadConfigResp.ProtoReflect.Descriptor instead.
func (*NotifyListenersReloadConfigResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{19}
}

type SetConfigSchemaReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Schema             *ConfigSchema          `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`                                                      // 配置协议
	AsyncCreateIndexes bool                   `protobuf:"varint,2,opt,name=async_create_indexes,json=asyncCreateIndexes,proto3" json:"async_create_indexes,omitempty"` // 是否异步创建配置集合版本
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetConfigSchemaReq) Reset() {
	*x = SetConfigSchemaReq{}
	mi := &file_configcenter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigSchemaReq) ProtoMessage() {}

func (x *SetConfigSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigSchemaReq.ProtoReflect.Descriptor instead.
func (*SetConfigSchemaReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{20}
}

func (x *SetConfigSchemaReq) GetSchema() *ConfigSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *SetConfigSchemaReq) GetAsyncCreateIndexes() bool {
	if x != nil {
		return x.AsyncCreateIndexes
	}
	return false
}

// 配置协议
type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollName      string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"`                  // 集合名称
	IndexKeys     []string               `protobuf:"bytes,2,rep,name=index_keys,json=indexKeys,proto3" json:"index_keys,omitempty"`               // 普通索引键
	UniqIndexKeys []string               `protobuf:"bytes,3,rep,name=uniq_index_keys,json=uniqIndexKeys,proto3" json:"uniq_index_keys,omitempty"` // 唯一索引键
	JsonSchema    string                 `protobuf:"bytes,4,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`            // json schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_configcenter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigSchema) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *ConfigSchema) GetIndexKeys() []string {
	if x != nil {
		return x.IndexKeys
	}
	return nil
}

func (x *ConfigSchema) GetUniqIndexKeys() []string {
	if x != nil {
		return x.UniqIndexKeys
	}
	return nil
}

func (x *ConfigSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

type SetConfigSchemaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigSchemaResp) Reset() {
	*x = SetConfigSchemaResp{}
	mi := &file_configcenter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigSchemaResp) ProtoMessage() {}

func (x *SetConfigSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigSchemaResp.ProtoReflect.Descriptor instead.
func (*SetConfigSchemaResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{22}
}

type GetConfigSchemaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollName      string                 `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"` // 集合名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaReq) Reset() {
	*x = GetConfigSchemaReq{}
	mi := &file_configcenter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaReq) ProtoMessage() {}

func (x *GetConfigSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaReq.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaReq) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{23}
}

func (x *GetConfigSchemaReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

type GetConfigSchemaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *ConfigSchema          `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // 配置协议
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaResp) Reset() {
	*x = GetConfigSchemaResp{}
	mi := &file_configcenter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaResp) ProtoMessage() {}

func (x *GetConfigSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaResp.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaResp) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{24}
}

func (x *GetConfigSchemaResp) GetSchema() *ConfigSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ListConfigReq_Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                     // 排序字段
	SortWay       int32                  `protobuf:"varint,2,opt,name=sort_way,json=sortWay,proto3" json:"sort_way,omitempty"` // 排序方式，1升序或者-1降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq_Sort) Reset() {
	*x = ListConfigReq_Sort{}
	mi := &file_configcenter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq_Sort) ProtoMessage() {}

func (x *ListConfigReq_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq_Sort.ProtoReflect.Descriptor instead.
func (*ListConfigReq_Sort) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ListConfigReq_Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListConfigReq_Sort) GetSortWay() int32 {
	if x != nil {
		return x.SortWay
	}
	return 0
}

type ListConfigReq_Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Selected      int32                  `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq_Selector) Reset() {
	*x = ListConfigReq_Selector{}
	mi := &file_configcenter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq_Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq_Selector) ProtoMessage() {}

func (x *ListConfigReq_Selector) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq_Selector.ProtoReflect.Descriptor instead.
func (*ListConfigReq_Selector) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{16, 1}
}

func (x *ListConfigReq_Selector) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListConfigReq_Selector) GetSelected() int32 {
	if x != nil {
		return x.Selected
	}
	return 0
}

var File_configcenter_proto protoreflect.FileDescriptor

const file_configcenter_proto_rawDesc = "" +
	"\n" +
	"\x12configcenter.proto\x12\fconfigcenter\x1a\x13easymicro_ext.proto\x1a\x0fmgorm_ext.proto\x1a\fcommon.proto\"\x99\x01\n" +
	"\x0eSetKeyValueReq\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.common.KVConfigR\x06config\x126\n" +
	"\x17should_notify_listeners\x18\x02 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x03 \x01(\tR\rlistenerGroup\"\x11\n" +
	"\x0fSetKeyValueResp\"\"\n" +
	"\x0eGetKeyValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"K\n" +
	"\x0fGetKeyValueResp\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.common.KVConfigR\x06config\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xa3\x01\n" +
	"\rAddConfigsReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06values\x126\n" +
	"\x17should_notify_listeners\x18\x03 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x04 \x01(\tR\rlistenerGroup\"/\n" +
	"\x0eAddConfigsResp\x12\x1d\n" +
	"\n" +
	"config_ids\x18\x01 \x03(\tR\tconfigIds\"\xb6\x01\n" +
	"\x10UpdateConfigsReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x126\n" +
	"\x17should_notify_listeners\x18\x04 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x05 \x01(\tR\rlistenerGroup\"\x13\n" +
	"\x11UpdateConfigsResp\"\xa0\x01\n" +
	"\fAddConfigReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x126\n" +
	"\x17should_notify_listeners\x18\x03 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x04 \x01(\tR\rlistenerGroup\",\n" +
	"\rAddConfigResp\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\"\xb3\x01\n" +
	"\x0fUpdateConfigReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x126\n" +
	"\x17should_notify_listeners\x18\x04 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x05 \x01(\tR\rlistenerGroup\"\x12\n" +
	"\x10UpdateConfigResp\"\x9d\x01\n" +
	"\x0fDeleteConfigReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x126\n" +
	"\x17should_notify_listeners\x18\x03 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x04 \x01(\tR\rlistenerGroup\"\x12\n" +
	"\x10DeleteConfigResp\"\xa0\x01\n" +
	"\x10DeleteConfigsReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x126\n" +
	"\x17should_notify_listeners\x18\x03 \x01(\bR\x15shouldNotifyListeners\x12%\n" +
	"\x0elistener_group\x18\x04 \x01(\tR\rlistenerGroup\"\x13\n" +
	"\x11DeleteConfigsResp\"\xe5\x02\n" +
	"\rListConfigReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x126\n" +
	"\x05sorts\x18\x04 \x03(\v2 .configcenter.ListConfigReq.SortR\x05sorts\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\fR\x06filter\x12B\n" +
	"\tselectors\x18\x06 \x03(\v2$.configcenter.ListConfigReq.SelectorR\tselectors\x1a7\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x19\n" +
	"\bsort_way\x18\x02 \x01(\x05R\asortWay\x1a<\n" +
	"\bSelector\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\x05R\bselected\":\n" +
	"\x0eListConfigResp\x12\x12\n" +
	"\x04list\x18\x01 \x03(\fR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\x92\x01\n" +
	"\x1eNotifyListenersReloadConfigReq\x12%\n" +
	"\x0elistener_group\x18\x01 \x01(\tR\rlistenerGroup\x12\x1d\n" +
	"\n" +
	"coll_names\x18\x02 \x03(\tR\tcollNames\x12*\n" +
	"\x11should_reload_all\x18\x03 \x01(\bR\x0fshouldReloadAll\"!\n" +
	"\x1fNotifyListenersReloadConfigResp\"z\n" +
	"\x12SetConfigSchemaReq\x122\n" +
	"\x06schema\x18\x01 \x01(\v2\x1a.configcenter.ConfigSchemaR\x06schema\x120\n" +
	"\x14async_create_indexes\x18\x02 \x01(\bR\x12asyncCreateIndexes\"\xdd\x01\n" +
	"\fConfigSchema\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x1d\n" +
	"\n" +
	"index_keys\x18\x02 \x03(\tR\tindexKeys\x12&\n" +
	"\x0funiq_index_keys\x18\x03 \x03(\tR\runiqIndexKeys\x12\x1f\n" +
	"\vjson_schema\x18\x04 \x01(\tR\n" +
	"jsonSchema:H\x8a\x9d \x06\"\x04bson\x8a\x8e%:\n" +
	"\rmconfigcenter\x12\rmconfigcenter\x1a\rconfig_schema:\tcoll_nameP\x01\"\x15\n" +
	"\x13SetConfigSchemaResp\"1\n" +
	"\x12GetConfigSchemaReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\"I\n" +
	"\x13GetConfigSchemaResp\x122\n" +
	"\x06schema\x18\x01 \x01(\v2\x1a.configcenter.ConfigSchemaR\x06schema*\x93\x01\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12\x18\n" +
	"\x13ErrCodeParamInvalid\x10\xe9\a\x12 \n" +
	"\x1bErrCodeConfigSchemaNotFound\x10\xea\a\x12 \n" +
	"\x1bErrCodeValidateSchemaFailed\x10\xeb\a\x12\x1a\n" +
	"\x15ErrCodeConfigNotFound\x10\xec\a2\xec\a\n" +
	"\fConfigCenter\x12D\n" +
	"\tAddConfig\x12\x1a.configcenter.AddConfigReq\x1a\x1b.configcenter.AddConfigResp\x12G\n" +
	"\n" +
	"AddConfigs\x12\x1b.configcenter.AddConfigsReq\x1a\x1c.configcenter.AddConfigsResp\x12M\n" +
	"\fUpdateConfig\x12\x1d.configcenter.UpdateConfigReq\x1a\x1e.configcenter.UpdateConfigResp\x12P\n" +
	"\rUpdateConfigs\x12\x1e.configcenter.UpdateConfigsReq\x1a\x1f.configcenter.UpdateConfigsResp\x12M\n" +
	"\fDeleteConfig\x12\x1d.configcenter.DeleteConfigReq\x1a\x1e.configcenter.DeleteConfigResp\x12P\n" +
	"\rDeleteConfigs\x12\x1e.configcenter.DeleteConfigsReq\x1a\x1f.configcenter.DeleteConfigsResp\x12G\n" +
	"\n" +
	"ListConfig\x12\x1b.configcenter.ListConfigReq\x1a\x1c.configcenter.ListConfigResp\x12z\n" +
	"\x1bNotifyListenersReloadConfig\x12,.configcenter.NotifyListenersReloadConfigReq\x1a-.configcenter.NotifyListenersReloadConfigResp\x12V\n" +
	"\x0fSetConfigSchema\x12 .configcenter.SetConfigSchemaReq\x1a!.configcenter.SetConfigSchemaResp\x12V\n" +
	"\x0fGetConfigSchema\x12 .configcenter.GetConfigSchemaReq\x1a!.configcenter.GetConfigSchemaResp\x12J\n" +
	"\vSetKeyValue\x12\x1c.configcenter.SetKeyValueReq\x1a\x1d.configcenter.SetKeyValueResp\x12J\n" +
	"\vGetKeyValue\x12\x1c.configcenter.GetKeyValueReq\x1a\x1d.configcenter.GetKeyValueRespBW\x8a\x9d \" \x01@\x01Z\rmconfigcenterb\rmconfigcenterZ/github.com/995933447/mconfigcenter/configcenterb\x06proto3"

var (
	file_configcenter_proto_rawDescOnce sync.Once
	file_configcenter_proto_rawDescData []byte
)

func file_configcenter_proto_rawDescGZIP() []byte {
	file_configcenter_proto_rawDescOnce.Do(func() {
		file_configcenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)))
	})
	return file_configcenter_proto_rawDescData
}

var file_configcenter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_configcenter_proto_goTypes = []any{
	(ErrCode)(0),                            // 0: configcenter.ErrCode
	(*SetKeyValueReq)(nil),                  // 1: configcenter.SetKeyValueReq
	(*SetKeyValueResp)(nil),                 // 2: configcenter.SetKeyValueResp
	(*GetKeyValueReq)(nil),                  // 3: configcenter.GetKeyValueReq
	(*GetKeyValueResp)(nil),                 // 4: configcenter.GetKeyValueResp
	(*AddConfigsReq)(nil),                   // 5: configcenter.AddConfigsReq
	(*AddConfigsResp)(nil),                  // 6: configcenter.AddConfigsResp
	(*UpdateConfigsReq)(nil),                // 7: configcenter.UpdateConfigsReq
	(*UpdateConfigsResp)(nil),               // 8: configcenter.UpdateConfigsResp
	(*AddConfigReq)(nil),                    // 9: configcenter.AddConfigReq
	(*AddConfigResp)(nil),                   // 10: configcenter.AddConfigResp
	(*UpdateConfigReq)(nil),                 // 11: configcenter.UpdateConfigReq
	(*UpdateConfigResp)(nil),                // 12: configcenter.UpdateConfigResp
	(*DeleteConfigReq)(nil),                 // 13: configcenter.DeleteConfigReq
	(*DeleteConfigResp)(nil),                // 14: configcenter.DeleteConfigResp
	(*DeleteConfigsReq)(nil),                // 15: configcenter.DeleteConfigsReq
	(*DeleteConfigsResp)(nil),               // 16: configcenter.DeleteConfigsResp
	(*ListConfigReq)(nil),                   // 17: configcenter.ListConfigReq
	(*ListConfigResp)(nil),                  // 18: configcenter.ListConfigResp
	(*NotifyListenersReloadConfigReq)(nil),  // 19: configcenter.NotifyListenersReloadConfigReq
	(*NotifyListenersReloadConfigResp)(nil), // 20: configcenter.NotifyListenersReloadConfigResp
	(*SetConfigSchemaReq)(nil),              // 21: configcenter.SetConfigSchemaReq
	(*ConfigSchema)(nil),                    // 22: configcenter.ConfigSchema
	(*SetConfigSchemaResp)(nil),             // 23: configcenter.SetConfigSchemaResp
	(*GetConfigSchemaReq)(nil),              // 24: configcenter.GetConfigSchemaReq
	(*GetConfigSchemaResp)(nil),             // 25: configcenter.GetConfigSchemaResp
	(*ListConfigReq_Sort)(nil),              // 26: configcenter.ListConfigReq.Sort
	(*ListConfigReq_Selector)(nil),          // 27: configcenter.ListConfigReq.Selector
	(*common.KVConfig)(nil),                 // 28: common.KVConfig
}
var file_configcenter_proto_depIdxs = []int32{
	28, // 0: configcenter.SetKeyValueReq.config:type_name -> common.KVConfig
	28, // 1: configcenter.GetKeyValueResp.config:type_name -> common.KVConfig
	26, // 2: configcenter.ListConfigReq.sorts:type_name -> configcenter.ListConfigReq.Sort
	27, // 3: configcenter.ListConfigReq.selectors:type_name -> configcenter.ListConfigReq.Selector
	22, // 4: configcenter.SetConfigSchemaReq.schema:type_name -> configcenter.ConfigSchema
	22, // 5: configcenter.GetConfigSchemaResp.schema:type_name -> configcenter.ConfigSchema
	9,  // 6: configcenter.ConfigCenter.AddConfig:input_type -> configcenter.AddConfigReq
	5,  // 7: configcenter.ConfigCenter.AddConfigs:input_type -> configcenter.AddConfigsReq
	11, // 8: configcenter.ConfigCenter.UpdateConfig:input_type -> configcenter.UpdateConfigReq
	7,  // 9: configcenter.ConfigCenter.UpdateConfigs:input_type -> configcenter.UpdateConfigsReq
	13, // 10: configcenter.ConfigCenter.DeleteConfig:input_type -> configcenter.DeleteConfigReq
	15, // 11: configcenter.ConfigCenter.DeleteConfigs:input_type -> configcenter.DeleteConfigsReq
	17, // 12: configcenter.ConfigCenter.ListConfig:input_type -> configcenter.ListConfigReq
	19, // 13: configcenter.ConfigCenter.NotifyListenersReloadConfig:input_type -> configcenter.NotifyListenersReloadConfigReq
	21, // 14: configcenter.ConfigCenter.SetConfigSchema:input_type -> configcenter.SetConfigSchemaReq
	24, // 15: configcenter.ConfigCenter.GetConfigSchema:input_type -> configcenter.GetConfigSchemaReq
	1,  // 16: configcenter.ConfigCenter.SetKeyValue:input_type -> configcenter.SetKeyValueReq
	3,  // 17: configcenter.ConfigCenter.GetKeyValue:input_type -> configcenter.GetKeyValueReq
	10, // 18: configcenter.ConfigCenter.AddConfig:output_type -> configcenter.AddConfigResp
	6,  // 19: configcenter.ConfigCenter.AddConfigs:output_type -> configcenter.AddConfigsResp
	12, // 20: configcenter.ConfigCenter.UpdateConfig:output_type -> configcenter.UpdateConfigResp
	8,  // 21: configcenter.ConfigCenter.UpdateConfigs:output_type -> configcenter.UpdateConfigsResp
	14, // 22: configcenter.ConfigCenter.DeleteConfig:output_type -> configcenter.DeleteConfigResp
	16, // 23: configcenter.ConfigCenter.DeleteConfigs:output_type -> configcenter.DeleteConfigsResp
	18, // 24: configcenter.ConfigCenter.ListConfig:output_type -> configcenter.ListConfigResp
	20, // 25: configcenter.ConfigCenter.NotifyListenersReloadConfig:output_type -> configcenter.NotifyListenersReloadConfigResp
	23, // 26: configcenter.ConfigCenter.SetConfigSchema:output_type -> configcenter.SetConfigSchemaResp
	25, // 27: configcenter.ConfigCenter.GetConfigSchema:output_type -> configcenter.GetConfigSchemaResp
	2,  // 28: configcenter.ConfigCenter.SetKeyValue:output_type -> configcenter.SetKeyValueResp
	4,  // 29: configcenter.ConfigCenter.GetKeyValue:output_type -> configcenter.GetKeyValueResp
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_configcenter_proto_init() }
func file_configcenter_proto_init() {
	if File_configcenter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configcenter_proto_goTypes,
		DependencyIndexes: file_configcenter_proto_depIdxs,
		EnumInfos:         file_configcenter_proto_enumTypes,
		MessageInfos:      file_configcenter_proto_msgTypes,
	}.Build()
	File_configcenter_proto = out.File
	file_configcenter_proto_goTypes = nil
	file_configcenter_proto_depIdxs = nil
}
