// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package configcenter

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "mconfigcenter"
	EasymicroDiscoveryName = "mconfigcenter"
)

const EasymicroGRPCPbServiceNameConfigCenter = "configcenter.ConfigCenter"

var ConfigCenterDefault = &ConfigCenter{}

func ConfigCenterGRPC() *ConfigCenter {
	return ConfigCenterDefault
}

func NewConfigCenterGRPC(dialOpts ...grpc.DialOption) *ConfigCenter {
	return &ConfigCenter{
		dialOpts: dialOpts,
	}
}

type ConfigCenter struct {
	c        ConfigCenterClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *ConfigCenter) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *ConfigCenter) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameConfigCenter)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameConfigCenter, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewConfigCenterClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *ConfigCenter) AddConfig(ctx context.Context, in *AddConfigReq, opts ...grpc.CallOption) (*AddConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddConfig(ctx, in, opts...)
}

func (s *ConfigCenter) AddConfigs(ctx context.Context, in *AddConfigsReq, opts ...grpc.CallOption) (*AddConfigsResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddConfigs(ctx, in, opts...)
}

func (s *ConfigCenter) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateConfig(ctx, in, opts...)
}

func (s *ConfigCenter) UpdateConfigs(ctx context.Context, in *UpdateConfigsReq, opts ...grpc.CallOption) (*UpdateConfigsResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateConfigs(ctx, in, opts...)
}

func (s *ConfigCenter) DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteConfig(ctx, in, opts...)
}

func (s *ConfigCenter) DeleteConfigs(ctx context.Context, in *DeleteConfigsReq, opts ...grpc.CallOption) (*DeleteConfigsResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteConfigs(ctx, in, opts...)
}

func (s *ConfigCenter) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListConfig(ctx, in, opts...)
}

func (s *ConfigCenter) NotifyListenersReloadConfig(ctx context.Context, in *NotifyListenersReloadConfigReq, opts ...grpc.CallOption) (*NotifyListenersReloadConfigResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.NotifyListenersReloadConfig(ctx, in, opts...)
}

func (s *ConfigCenter) SetConfigSchema(ctx context.Context, in *SetConfigSchemaReq, opts ...grpc.CallOption) (*SetConfigSchemaResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetConfigSchema(ctx, in, opts...)
}

func (s *ConfigCenter) GetConfigSchema(ctx context.Context, in *GetConfigSchemaReq, opts ...grpc.CallOption) (*GetConfigSchemaResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetConfigSchema(ctx, in, opts...)
}

func (s *ConfigCenter) SetKeyValue(ctx context.Context, in *SetKeyValueReq, opts ...grpc.CallOption) (*SetKeyValueResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetKeyValue(ctx, in, opts...)
}

func (s *ConfigCenter) GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetKeyValue(ctx, in, opts...)
}

func (s *ConfigCenter) ListConfigSchema(ctx context.Context, in *ListConfigSchemaReq, opts ...grpc.CallOption) (*ListConfigSchemaResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListConfigSchema(ctx, in, opts...)
}
