// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: configcenter.proto

package configcenter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigCenter_AddConfig_FullMethodName                   = "/configcenter.ConfigCenter/AddConfig"
	ConfigCenter_AddConfigs_FullMethodName                  = "/configcenter.ConfigCenter/AddConfigs"
	ConfigCenter_UpdateConfig_FullMethodName                = "/configcenter.ConfigCenter/UpdateConfig"
	ConfigCenter_UpdateConfigs_FullMethodName               = "/configcenter.ConfigCenter/UpdateConfigs"
	ConfigCenter_DeleteConfig_FullMethodName                = "/configcenter.ConfigCenter/DeleteConfig"
	ConfigCenter_DeleteConfigs_FullMethodName               = "/configcenter.ConfigCenter/DeleteConfigs"
	ConfigCenter_ListConfig_FullMethodName                  = "/configcenter.ConfigCenter/ListConfig"
	ConfigCenter_NotifyListenersReloadConfig_FullMethodName = "/configcenter.ConfigCenter/NotifyListenersReloadConfig"
	ConfigCenter_SetConfigSchema_FullMethodName             = "/configcenter.ConfigCenter/SetConfigSchema"
	ConfigCenter_GetConfigSchema_FullMethodName             = "/configcenter.ConfigCenter/GetConfigSchema"
	ConfigCenter_SetKeyValue_FullMethodName                 = "/configcenter.ConfigCenter/SetKeyValue"
	ConfigCenter_GetKeyValue_FullMethodName                 = "/configcenter.ConfigCenter/GetKeyValue"
)

// ConfigCenterClient is the client API for ConfigCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 基于mongo db存储实现的配置中心服务
type ConfigCenterClient interface {
	// 添加一条配置到配置集合中
	AddConfig(ctx context.Context, in *AddConfigReq, opts ...grpc.CallOption) (*AddConfigResp, error)
	// 披露添加配置到配置集合中
	AddConfigs(ctx context.Context, in *AddConfigsReq, opts ...grpc.CallOption) (*AddConfigsResp, error)
	// 更新一条集合中的配置
	UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error)
	// 批量更新配置到集合中
	UpdateConfigs(ctx context.Context, in *UpdateConfigsReq, opts ...grpc.CallOption) (*UpdateConfigsResp, error)
	// 删除一条集合中的配置
	DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error)
	// 批量删除集合中的配置
	DeleteConfigs(ctx context.Context, in *DeleteConfigsReq, opts ...grpc.CallOption) (*DeleteConfigsResp, error)
	// 获取配置集合
	ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error)
	// 通知监听者重载配置
	NotifyListenersReloadConfig(ctx context.Context, in *NotifyListenersReloadConfigReq, opts ...grpc.CallOption) (*NotifyListenersReloadConfigResp, error)
	// 设置配置协议
	SetConfigSchema(ctx context.Context, in *SetConfigSchemaReq, opts ...grpc.CallOption) (*SetConfigSchemaResp, error)
	// 获取配置协议
	GetConfigSchema(ctx context.Context, in *GetConfigSchemaReq, opts ...grpc.CallOption) (*GetConfigSchemaResp, error)
	// 设置键值配置
	SetKeyValue(ctx context.Context, in *SetKeyValueReq, opts ...grpc.CallOption) (*SetKeyValueResp, error)
	// 获取键值配置
	GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error)
}

type configCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigCenterClient(cc grpc.ClientConnInterface) ConfigCenterClient {
	return &configCenterClient{cc}
}

func (c *configCenterClient) AddConfig(ctx context.Context, in *AddConfigReq, opts ...grpc.CallOption) (*AddConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddConfigResp)
	err := c.cc.Invoke(ctx, ConfigCenter_AddConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) AddConfigs(ctx context.Context, in *AddConfigsReq, opts ...grpc.CallOption) (*AddConfigsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddConfigsResp)
	err := c.cc.Invoke(ctx, ConfigCenter_AddConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*UpdateConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResp)
	err := c.cc.Invoke(ctx, ConfigCenter_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) UpdateConfigs(ctx context.Context, in *UpdateConfigsReq, opts ...grpc.CallOption) (*UpdateConfigsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigsResp)
	err := c.cc.Invoke(ctx, ConfigCenter_UpdateConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) DeleteConfig(ctx context.Context, in *DeleteConfigReq, opts ...grpc.CallOption) (*DeleteConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResp)
	err := c.cc.Invoke(ctx, ConfigCenter_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) DeleteConfigs(ctx context.Context, in *DeleteConfigsReq, opts ...grpc.CallOption) (*DeleteConfigsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigsResp)
	err := c.cc.Invoke(ctx, ConfigCenter_DeleteConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigResp)
	err := c.cc.Invoke(ctx, ConfigCenter_ListConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) NotifyListenersReloadConfig(ctx context.Context, in *NotifyListenersReloadConfigReq, opts ...grpc.CallOption) (*NotifyListenersReloadConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyListenersReloadConfigResp)
	err := c.cc.Invoke(ctx, ConfigCenter_NotifyListenersReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) SetConfigSchema(ctx context.Context, in *SetConfigSchemaReq, opts ...grpc.CallOption) (*SetConfigSchemaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigSchemaResp)
	err := c.cc.Invoke(ctx, ConfigCenter_SetConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) GetConfigSchema(ctx context.Context, in *GetConfigSchemaReq, opts ...grpc.CallOption) (*GetConfigSchemaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigSchemaResp)
	err := c.cc.Invoke(ctx, ConfigCenter_GetConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) SetKeyValue(ctx context.Context, in *SetKeyValueReq, opts ...grpc.CallOption) (*SetKeyValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetKeyValueResp)
	err := c.cc.Invoke(ctx, ConfigCenter_SetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyValueResp)
	err := c.cc.Invoke(ctx, ConfigCenter_GetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigCenterServer is the server API for ConfigCenter service.
// All implementations must embed UnimplementedConfigCenterServer
// for forward compatibility.
//
// 基于mongo db存储实现的配置中心服务
type ConfigCenterServer interface {
	// 添加一条配置到配置集合中
	AddConfig(context.Context, *AddConfigReq) (*AddConfigResp, error)
	// 披露添加配置到配置集合中
	AddConfigs(context.Context, *AddConfigsReq) (*AddConfigsResp, error)
	// 更新一条集合中的配置
	UpdateConfig(context.Context, *UpdateConfigReq) (*UpdateConfigResp, error)
	// 批量更新配置到集合中
	UpdateConfigs(context.Context, *UpdateConfigsReq) (*UpdateConfigsResp, error)
	// 删除一条集合中的配置
	DeleteConfig(context.Context, *DeleteConfigReq) (*DeleteConfigResp, error)
	// 批量删除集合中的配置
	DeleteConfigs(context.Context, *DeleteConfigsReq) (*DeleteConfigsResp, error)
	// 获取配置集合
	ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error)
	// 通知监听者重载配置
	NotifyListenersReloadConfig(context.Context, *NotifyListenersReloadConfigReq) (*NotifyListenersReloadConfigResp, error)
	// 设置配置协议
	SetConfigSchema(context.Context, *SetConfigSchemaReq) (*SetConfigSchemaResp, error)
	// 获取配置协议
	GetConfigSchema(context.Context, *GetConfigSchemaReq) (*GetConfigSchemaResp, error)
	// 设置键值配置
	SetKeyValue(context.Context, *SetKeyValueReq) (*SetKeyValueResp, error)
	// 获取键值配置
	GetKeyValue(context.Context, *GetKeyValueReq) (*GetKeyValueResp, error)
	mustEmbedUnimplementedConfigCenterServer()
}

// UnimplementedConfigCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigCenterServer struct{}

func (UnimplementedConfigCenterServer) AddConfig(context.Context, *AddConfigReq) (*AddConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConfig not implemented")
}
func (UnimplementedConfigCenterServer) AddConfigs(context.Context, *AddConfigsReq) (*AddConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConfigs not implemented")
}
func (UnimplementedConfigCenterServer) UpdateConfig(context.Context, *UpdateConfigReq) (*UpdateConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedConfigCenterServer) UpdateConfigs(context.Context, *UpdateConfigsReq) (*UpdateConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigs not implemented")
}
func (UnimplementedConfigCenterServer) DeleteConfig(context.Context, *DeleteConfigReq) (*DeleteConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConfigCenterServer) DeleteConfigs(context.Context, *DeleteConfigsReq) (*DeleteConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfigs not implemented")
}
func (UnimplementedConfigCenterServer) ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfig not implemented")
}
func (UnimplementedConfigCenterServer) NotifyListenersReloadConfig(context.Context, *NotifyListenersReloadConfigReq) (*NotifyListenersReloadConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyListenersReloadConfig not implemented")
}
func (UnimplementedConfigCenterServer) SetConfigSchema(context.Context, *SetConfigSchemaReq) (*SetConfigSchemaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfigSchema not implemented")
}
func (UnimplementedConfigCenterServer) GetConfigSchema(context.Context, *GetConfigSchemaReq) (*GetConfigSchemaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigSchema not implemented")
}
func (UnimplementedConfigCenterServer) SetKeyValue(context.Context, *SetKeyValueReq) (*SetKeyValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKeyValue not implemented")
}
func (UnimplementedConfigCenterServer) GetKeyValue(context.Context, *GetKeyValueReq) (*GetKeyValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (UnimplementedConfigCenterServer) mustEmbedUnimplementedConfigCenterServer() {}
func (UnimplementedConfigCenterServer) testEmbeddedByValue()                      {}

// UnsafeConfigCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigCenterServer will
// result in compilation errors.
type UnsafeConfigCenterServer interface {
	mustEmbedUnimplementedConfigCenterServer()
}

func RegisterConfigCenterServer(s grpc.ServiceRegistrar, srv ConfigCenterServer) {
	// If the following call pancis, it indicates UnimplementedConfigCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigCenter_ServiceDesc, srv)
}

func _ConfigCenter_AddConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).AddConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_AddConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).AddConfig(ctx, req.(*AddConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_AddConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).AddConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_AddConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).AddConfigs(ctx, req.(*AddConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).UpdateConfig(ctx, req.(*UpdateConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_UpdateConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).UpdateConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_UpdateConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).UpdateConfigs(ctx, req.(*UpdateConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).DeleteConfig(ctx, req.(*DeleteConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_DeleteConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).DeleteConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_DeleteConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).DeleteConfigs(ctx, req.(*DeleteConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_ListConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).ListConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_ListConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).ListConfig(ctx, req.(*ListConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_NotifyListenersReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyListenersReloadConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).NotifyListenersReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_NotifyListenersReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).NotifyListenersReloadConfig(ctx, req.(*NotifyListenersReloadConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_SetConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).SetConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_SetConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).SetConfigSchema(ctx, req.(*SetConfigSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_GetConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).GetConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_GetConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).GetConfigSchema(ctx, req.(*GetConfigSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_SetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).SetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_SetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).SetKeyValue(ctx, req.(*SetKeyValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_GetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).GetKeyValue(ctx, req.(*GetKeyValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigCenter_ServiceDesc is the grpc.ServiceDesc for ConfigCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configcenter.ConfigCenter",
	HandlerType: (*ConfigCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddConfig",
			Handler:    _ConfigCenter_AddConfig_Handler,
		},
		{
			MethodName: "AddConfigs",
			Handler:    _ConfigCenter_AddConfigs_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _ConfigCenter_UpdateConfig_Handler,
		},
		{
			MethodName: "UpdateConfigs",
			Handler:    _ConfigCenter_UpdateConfigs_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ConfigCenter_DeleteConfig_Handler,
		},
		{
			MethodName: "DeleteConfigs",
			Handler:    _ConfigCenter_DeleteConfigs_Handler,
		},
		{
			MethodName: "ListConfig",
			Handler:    _ConfigCenter_ListConfig_Handler,
		},
		{
			MethodName: "NotifyListenersReloadConfig",
			Handler:    _ConfigCenter_NotifyListenersReloadConfig_Handler,
		},
		{
			MethodName: "SetConfigSchema",
			Handler:    _ConfigCenter_SetConfigSchema_Handler,
		},
		{
			MethodName: "GetConfigSchema",
			Handler:    _ConfigCenter_GetConfigSchema_Handler,
		},
		{
			MethodName: "SetKeyValue",
			Handler:    _ConfigCenter_SetKeyValue_Handler,
		},
		{
			MethodName: "GetKeyValue",
			Handler:    _ConfigCenter_GetKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configcenter.proto",
}
