// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: biz.proto

package biz

import (
	_ "github.com/995933447/easymicro/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVipMaxLevelLimitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVipMaxLevelLimitReq) Reset() {
	*x = GetVipMaxLevelLimitReq{}
	mi := &file_biz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVipMaxLevelLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVipMaxLevelLimitReq) ProtoMessage() {}

func (x *GetVipMaxLevelLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVipMaxLevelLimitReq.ProtoReflect.Descriptor instead.
func (*GetVipMaxLevelLimitReq) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{0}
}

type GetVipMaxLevelLimitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVipMaxLevelLimitResp) Reset() {
	*x = GetVipMaxLevelLimitResp{}
	mi := &file_biz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVipMaxLevelLimitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVipMaxLevelLimitResp) ProtoMessage() {}

func (x *GetVipMaxLevelLimitResp) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVipMaxLevelLimitResp.ProtoReflect.Descriptor instead.
func (*GetVipMaxLevelLimitResp) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{1}
}

func (x *GetVipMaxLevelLimitResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_biz_proto protoreflect.FileDescriptor

const file_biz_proto_rawDesc = "" +
	"\n" +
	"\tbiz.proto\x12\x03biz\x1a\x13easymicro_ext.proto\"\x18\n" +
	"\x16GetVipMaxLevelLimitReq\"/\n" +
	"\x17GetVipMaxLevelLimitResp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level2W\n" +
	"\x03Biz\x12P\n" +
	"\x13GetVipMaxLevelLimit\x12\x1b.biz.GetVipMaxLevelLimitReq\x1a\x1c.biz.GetVipMaxLevelLimitRespBR\x8a\x9d \x1eZ\rmconfigcenterb\rmconfigcenterZ.github.com/995933447/mconfigcenter/example/bizb\x06proto3"

var (
	file_biz_proto_rawDescOnce sync.Once
	file_biz_proto_rawDescData []byte
)

func file_biz_proto_rawDescGZIP() []byte {
	file_biz_proto_rawDescOnce.Do(func() {
		file_biz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_biz_proto_rawDesc), len(file_biz_proto_rawDesc)))
	})
	return file_biz_proto_rawDescData
}

var file_biz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_biz_proto_goTypes = []any{
	(*GetVipMaxLevelLimitReq)(nil),  // 0: biz.GetVipMaxLevelLimitReq
	(*GetVipMaxLevelLimitResp)(nil), // 1: biz.GetVipMaxLevelLimitResp
}
var file_biz_proto_depIdxs = []int32{
	0, // 0: biz.Biz.GetVipMaxLevelLimit:input_type -> biz.GetVipMaxLevelLimitReq
	1, // 1: biz.Biz.GetVipMaxLevelLimit:output_type -> biz.GetVipMaxLevelLimitResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_biz_proto_init() }
func file_biz_proto_init() {
	if File_biz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biz_proto_rawDesc), len(file_biz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biz_proto_goTypes,
		DependencyIndexes: file_biz_proto_depIdxs,
		MessageInfos:      file_biz_proto_msgTypes,
	}.Build()
	File_biz_proto = out.File
	file_biz_proto_goTypes = nil
	file_biz_proto_depIdxs = nil
}
