// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: biz.proto

package biz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Biz_GetVipMaxLevelLimit_FullMethodName = "/biz.Biz/GetVipMaxLevelLimit"
)

// BizClient is the client API for Biz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BizClient interface {
	GetVipMaxLevelLimit(ctx context.Context, in *GetVipMaxLevelLimitReq, opts ...grpc.CallOption) (*GetVipMaxLevelLimitResp, error)
}

type bizClient struct {
	cc grpc.ClientConnInterface
}

func NewBizClient(cc grpc.ClientConnInterface) BizClient {
	return &bizClient{cc}
}

func (c *bizClient) GetVipMaxLevelLimit(ctx context.Context, in *GetVipMaxLevelLimitReq, opts ...grpc.CallOption) (*GetVipMaxLevelLimitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVipMaxLevelLimitResp)
	err := c.cc.Invoke(ctx, Biz_GetVipMaxLevelLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BizServer is the server API for Biz service.
// All implementations must embed UnimplementedBizServer
// for forward compatibility.
type BizServer interface {
	GetVipMaxLevelLimit(context.Context, *GetVipMaxLevelLimitReq) (*GetVipMaxLevelLimitResp, error)
	mustEmbedUnimplementedBizServer()
}

// UnimplementedBizServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBizServer struct{}

func (UnimplementedBizServer) GetVipMaxLevelLimit(context.Context, *GetVipMaxLevelLimitReq) (*GetVipMaxLevelLimitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipMaxLevelLimit not implemented")
}
func (UnimplementedBizServer) mustEmbedUnimplementedBizServer() {}
func (UnimplementedBizServer) testEmbeddedByValue()             {}

// UnsafeBizServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BizServer will
// result in compilation errors.
type UnsafeBizServer interface {
	mustEmbedUnimplementedBizServer()
}

func RegisterBizServer(s grpc.ServiceRegistrar, srv BizServer) {
	// If the following call pancis, it indicates UnimplementedBizServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Biz_ServiceDesc, srv)
}

func _Biz_GetVipMaxLevelLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVipMaxLevelLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BizServer).GetVipMaxLevelLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Biz_GetVipMaxLevelLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BizServer).GetVipMaxLevelLimit(ctx, req.(*GetVipMaxLevelLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Biz_ServiceDesc is the grpc.ServiceDesc for Biz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Biz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biz.Biz",
	HandlerType: (*BizServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVipMaxLevelLimit",
			Handler:    _Biz_GetVipMaxLevelLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "biz.proto",
}
