// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package biz

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "mconfigcenter"
	EasymicroDiscoveryName = "mconfigcenter"
)

const EasymicroGRPCPbServiceNameBiz = "biz.Biz"

var BizDefault = &Biz{}

func BizGRPC() *Biz {
	return BizDefault
}

func NewBizGRPC(dialOpts ...grpc.DialOption) *Biz {
	return &Biz{
		dialOpts: dialOpts,
	}
}

type Biz struct {
	c        BizClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *Biz) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *Biz) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameBiz)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameBiz, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewBizClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *Biz) GetVipMaxLevelLimit(ctx context.Context, in *GetVipMaxLevelLimitReq, opts ...grpc.CallOption) (*GetVipMaxLevelLimitResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetVipMaxLevelLimit(ctx, in, opts...)
}
