// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/mconfigcenter/configcenter"
	"github.com/995933447/mconfigcenter/configcenterserver/handler"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "AddConfig", handler.ConfigCenterHandler.AddConfig, func() *configcenter.AddConfigReq {
		return &configcenter.AddConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "AddConfigs", handler.ConfigCenterHandler.AddConfigs, func() *configcenter.AddConfigsReq {
		return &configcenter.AddConfigsReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "UpdateConfig", handler.ConfigCenterHandler.UpdateConfig, func() *configcenter.UpdateConfigReq {
		return &configcenter.UpdateConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "UpdateConfigs", handler.ConfigCenterHandler.UpdateConfigs, func() *configcenter.UpdateConfigsReq {
		return &configcenter.UpdateConfigsReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "DeleteConfig", handler.ConfigCenterHandler.DeleteConfig, func() *configcenter.DeleteConfigReq {
		return &configcenter.DeleteConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "DeleteConfigs", handler.ConfigCenterHandler.DeleteConfigs, func() *configcenter.DeleteConfigsReq {
		return &configcenter.DeleteConfigsReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "ListConfig", handler.ConfigCenterHandler.ListConfig, func() *configcenter.ListConfigReq {
		return &configcenter.ListConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "NotifyListenersReloadConfig", handler.ConfigCenterHandler.NotifyListenersReloadConfig, func() *configcenter.NotifyListenersReloadConfigReq {
		return &configcenter.NotifyListenersReloadConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "SetConfigSchema", handler.ConfigCenterHandler.SetConfigSchema, func() *configcenter.SetConfigSchemaReq {
		return &configcenter.SetConfigSchemaReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "GetConfigSchema", handler.ConfigCenterHandler.GetConfigSchema, func() *configcenter.GetConfigSchemaReq {
		return &configcenter.GetConfigSchemaReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "SetKeyValue", handler.ConfigCenterHandler.SetKeyValue, func() *configcenter.SetKeyValueReq {
		return &configcenter.SetKeyValueReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "GetKeyValue", handler.ConfigCenterHandler.GetKeyValue, func() *configcenter.GetKeyValueReq {
		return &configcenter.GetKeyValueReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configcenter.EasymicroGRPCPbServiceNameConfigCenter, "ListConfigSchema", handler.ConfigCenterHandler.ListConfigSchema, func() *configcenter.ListConfigSchemaReq {
		return &configcenter.ListConfigSchemaReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
