// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/mconfigcenter/configcenter"
	"github.com/995933447/mconfigcenter/configcenterserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	configcenter.EasymicroGRPCPbServiceNameConfigCenter,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	configcenter.RegisterConfigCenterServer(server, handler.ConfigCenterHandler)
	return nil
}
