// Code generated by protoc-gen-mgorm. DO NOT EDIT.
// Desc: key value配置
package common

import (
	"context"
	"fmt"
	"time"

	"github.com/995933447/mgorm"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const (
	KVConfigDbName   = "mconfigcenter"
	KVConfigTbName   = "kv_config"
	KVConfigConnName = "mconfigcenter"
)

// 索引
var kVConfigIndexKeys = []string{}

var kVConfigUniqueIndexKeys = []string{
	"key",
}

var kVConfigExpireIndexKeys = []string{}

type KVConfigOrm struct {
	ID        primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	Key       string             `json:"key" bson:"key" jsonschema:"title=键"`
	Value     string             `json:"value" bson:"value" jsonschema:"title=值"`
	Extra     string             `json:"extra" bson:"extra" jsonschema:"title=额外信息"`
	CreatedAt time.Time          `json:"created_at,omitempty" bson:"created_at,omitempty"`
	UpdatedAt time.Time          `json:"updated_at,omitempty" bson:"updated_at,omitempty"`
}

var kVConfigOrmCache mgorm.Cache

func SetKVConfigOrmCache(cache mgorm.Cache) {
	kVConfigOrmCache = cache
}

var onKVConfigOrmQueryDone mgorm.OnQueryDoneFunc

func SetKVConfigOrmOnQueryDone(fn mgorm.OnQueryDoneFunc) {
	onKVConfigOrmQueryDone = fn
}

func NewKVConfigModel() *KVConfigModel {
	cache := kVConfigOrmCache
	if cache == nil {
		cache = mgorm.DefaultCache
	}
	orm := mgorm.NewOrm(
		KVConfigConnName,
		KVConfigDbName,
		KVConfigTbName,
		false,
		cache,
		kVConfigIndexKeys,
		kVConfigUniqueIndexKeys,
		kVConfigExpireIndexKeys,
	)
	onQueryDoneFunc := onKVConfigOrmQueryDone
	if onQueryDoneFunc == nil {
		onQueryDoneFunc = mgorm.OnQueryDone
	}
	orm.SetOnQueryDone(onQueryDoneFunc)
	return &KVConfigModel{
		Model: mgorm.Model[KVConfigOrm]{
			Orm:    orm,
			Cached: false,
		},
	}
}

type KVConfigModel struct {
	mgorm.Model[KVConfigOrm]
}

func (m *KVConfigModel) NormalizeOrmForInsert(data *KVConfigOrm) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
	}
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.UpdatedAt = data.CreatedAt
}

func (m *KVConfigModel) InsertOneIgnoreConflict(ctx context.Context, data *KVConfigOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOneIgnoreConflict(ctx, data)
	return err
}

func (m *KVConfigModel) InsertOne(ctx context.Context, data *KVConfigOrm) error {
	m.NormalizeOrmForInsert(data)
	_, err := m.Model.InsertOne(ctx, data)
	return err
}

func (m *KVConfigModel) InsertMany(ctx context.Context, dataList []*KVConfigOrm) error {
	var ins []any
	for _, data := range dataList {
		m.NormalizeOrmForInsert(data)
		ins = append(ins, data)
	}
	_, err := m.Model.InsertMany(ctx, ins)
	return err
}

func (m *KVConfigModel) GetCacheKeys(data *KVConfigOrm) []string {
	var cacheKeys []string
	cacheKeys = append(cacheKeys, fmt.Sprintf("_id:%s", data.ID.Hex()))
	cacheKeys = append(cacheKeys, fmt.Sprintf(
		"key:%s", data.Key,
	))
	return cacheKeys
}

func (m *KVConfigModel) Update(ctx context.Context, data *KVConfigOrm) (*mongo.UpdateResult, error) {
	dataB, err := mgorm.ToBsonM(data)
	if err != nil {
		return nil, err
	}
	dataB["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": dataB["_id"]}, bson.M{"$set": dataB})
}

func (m *KVConfigModel) UpdateOne(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": data})
}

func (m *KVConfigModel) UpdateMany(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	data["updated_at"] = time.Now()
	return m.Model.UpdateMany(ctx, filter, bson.M{"$set": data})
}

func (m *KVConfigModel) Upsert(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$setOnInsert": insertData})
}

func (m *KVConfigModel) UpInc(ctx context.Context, filter any, data bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$inc": data, "$set": bson.M{"updated_at": time.Now()}, "$setOnInsert": insertData})
}

func (m *KVConfigModel) UpAndInc(ctx context.Context, filter any, data, incdata bson.M) (*mongo.UpdateResult, error) {
	insertData := bson.M{}
	data["updated_at"] = time.Now()
	insertData["created_at"] = time.Now()

	return m.Model.Upsert(ctx, filter, bson.M{"$set": data, "$inc": incdata, "$setOnInsert": insertData})
}

func (m *KVConfigModel) DeleteOne(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteOne(ctx, filter)
}

func (m *KVConfigModel) DeleteMany(ctx context.Context, filter any) (*mongo.DeleteResult, error) {
	return m.Model.DeleteMany(ctx, filter)
}

func (m *KVConfigModel) UpdateOneByID(ctx context.Context, id string, data bson.M) (*mongo.UpdateResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	data["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, bson.M{"_id": objId}, bson.M{"$set": data})
}

func (m *KVConfigModel) DeleteOneByID(ctx context.Context, id string) (*mongo.DeleteResult, error) {
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}

	return m.Model.DeleteOne(ctx, bson.M{"_id": objId})
}

func (m *KVConfigModel) FindOneByID(ctx context.Context, id string) (*KVConfigOrm, error) {
	var data KVConfigOrm
	objId, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	filter := bson.M{"_id": objId}
	cacheKey := fmt.Sprintf("_id:%s", id)
	err = m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *KVConfigModel) UpdateOneByKey(ctx context.Context, key string, update bson.M) (*mongo.UpdateResult, error) {
	filter := bson.M{}
	var data KVConfigOrm
	filter["key"] = key
	cacheKey := fmt.Sprintf(
		"key:%s",
		key,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}

	update["updated_at"] = time.Now()
	return m.Model.UpdateOne(ctx, filter, bson.M{"$set": update})
}

func (m *KVConfigModel) FindOneByKey(ctx context.Context, key string) (*KVConfigOrm, error) {
	var data KVConfigOrm
	filter := bson.M{}
	filter["key"] = key
	cacheKey := fmt.Sprintf(
		"key:%s",
		key,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (m *KVConfigModel) DeleteOneByKey(ctx context.Context, key string) (*mongo.DeleteResult, error) {
	var data KVConfigOrm
	filter := bson.M{}
	filter["key"] = key
	cacheKey := fmt.Sprintf(
		"key:%s",
		key,
	)
	err := m.Model.FindOneByCacheKey(ctx, filter, cacheKey, &data)
	if err == nil {
		defer m.Model.DelCache(m.GetCacheKeys(&data))
	} else if err != mongo.ErrNoDocuments {
		return nil, err
	}
	return m.Model.DeleteOne(ctx, filter)
}
