// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: configimage.proto

package configimage

import (
	_ "github.com/995933447/easymicro/pb"
	common "github.com/995933447/mconfigcenter/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListConfigReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CollName      string                    `protobuf:"bytes,1,opt,name=coll_name,json=collName,proto3" json:"coll_name,omitempty"` // 集合名称
	Offset        uint32                    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                    // 位移
	Limit         uint32                    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 条数
	Sorts         []*ListConfigReq_Sort     `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`                       // 排序
	Filter        []byte                    `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`                     // 过滤
	Selectors     []*ListConfigReq_Selector `protobuf:"bytes,6,rep,name=selectors,proto3" json:"selectors,omitempty"`               // 字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq) Reset() {
	*x = ListConfigReq{}
	mi := &file_configimage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq) ProtoMessage() {}

func (x *ListConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq.ProtoReflect.Descriptor instead.
func (*ListConfigReq) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{0}
}

func (x *ListConfigReq) GetCollName() string {
	if x != nil {
		return x.CollName
	}
	return ""
}

func (x *ListConfigReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConfigReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConfigReq) GetSorts() []*ListConfigReq_Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListConfigReq) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListConfigReq) GetSelectors() []*ListConfigReq_Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type ListConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          [][]byte               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigResp) Reset() {
	*x = ListConfigResp{}
	mi := &file_configimage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigResp) ProtoMessage() {}

func (x *ListConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigResp.ProtoReflect.Descriptor instead.
func (*ListConfigResp) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{1}
}

func (x *ListConfigResp) GetList() [][]byte {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListConfigResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetKeyValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueReq) Reset() {
	*x = GetKeyValueReq{}
	mi := &file_configimage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueReq) ProtoMessage() {}

func (x *GetKeyValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueReq.ProtoReflect.Descriptor instead.
func (*GetKeyValueReq) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKeyValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *common.KVConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyValueResp) Reset() {
	*x = GetKeyValueResp{}
	mi := &file_configimage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyValueResp) ProtoMessage() {}

func (x *GetKeyValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyValueResp.ProtoReflect.Descriptor instead.
func (*GetKeyValueResp) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyValueResp) GetConfig() *common.KVConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetKeyValueResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConfigReq_Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                     // 排序字段
	SortWay       int32                  `protobuf:"varint,2,opt,name=sort_way,json=sortWay,proto3" json:"sort_way,omitempty"` // 排序方式，1升序或者-1降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq_Sort) Reset() {
	*x = ListConfigReq_Sort{}
	mi := &file_configimage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq_Sort) ProtoMessage() {}

func (x *ListConfigReq_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq_Sort.ProtoReflect.Descriptor instead.
func (*ListConfigReq_Sort) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListConfigReq_Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListConfigReq_Sort) GetSortWay() int32 {
	if x != nil {
		return x.SortWay
	}
	return 0
}

type ListConfigReq_Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Selected      int32                  `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq_Selector) Reset() {
	*x = ListConfigReq_Selector{}
	mi := &file_configimage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq_Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq_Selector) ProtoMessage() {}

func (x *ListConfigReq_Selector) ProtoReflect() protoreflect.Message {
	mi := &file_configimage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq_Selector.ProtoReflect.Descriptor instead.
func (*ListConfigReq_Selector) Descriptor() ([]byte, []int) {
	return file_configimage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ListConfigReq_Selector) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ListConfigReq_Selector) GetSelected() int32 {
	if x != nil {
		return x.Selected
	}
	return 0
}

var File_configimage_proto protoreflect.FileDescriptor

const file_configimage_proto_rawDesc = "" +
	"\n" +
	"\x11configimage.proto\x12\vconfigimage\x1a\x13easymicro_ext.proto\x1a\fcommon.proto\"\xe3\x02\n" +
	"\rListConfigReq\x12\x1b\n" +
	"\tcoll_name\x18\x01 \x01(\tR\bcollName\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x125\n" +
	"\x05sorts\x18\x04 \x03(\v2\x1f.configimage.ListConfigReq.SortR\x05sorts\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\fR\x06filter\x12A\n" +
	"\tselectors\x18\x06 \x03(\v2#.configimage.ListConfigReq.SelectorR\tselectors\x1a7\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x19\n" +
	"\bsort_way\x18\x02 \x01(\x05R\asortWay\x1a<\n" +
	"\bSelector\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\x05R\bselected\":\n" +
	"\x0eListConfigResp\x12\x12\n" +
	"\x04list\x18\x01 \x03(\fR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\"\n" +
	"\x0eGetKeyValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"K\n" +
	"\x0fGetKeyValueResp\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.common.KVConfigR\x06config\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\x9e\x01\n" +
	"\vConfigImage\x12E\n" +
	"\n" +
	"ListConfig\x12\x1a.configimage.ListConfigReq\x1a\x1b.configimage.ListConfigResp\x12H\n" +
	"\vGetKeyValue\x12\x1b.configimage.GetKeyValueReq\x1a\x1c.configimage.GetKeyValueRespBY\x8a\x9d %Z\x10mconfigcenterimgb\x11mconfigcenter_imgZ.github.com/995933447/mconfigcenter/configimageb\x06proto3"

var (
	file_configimage_proto_rawDescOnce sync.Once
	file_configimage_proto_rawDescData []byte
)

func file_configimage_proto_rawDescGZIP() []byte {
	file_configimage_proto_rawDescOnce.Do(func() {
		file_configimage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configimage_proto_rawDesc), len(file_configimage_proto_rawDesc)))
	})
	return file_configimage_proto_rawDescData
}

var file_configimage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_configimage_proto_goTypes = []any{
	(*ListConfigReq)(nil),          // 0: configimage.ListConfigReq
	(*ListConfigResp)(nil),         // 1: configimage.ListConfigResp
	(*GetKeyValueReq)(nil),         // 2: configimage.GetKeyValueReq
	(*GetKeyValueResp)(nil),        // 3: configimage.GetKeyValueResp
	(*ListConfigReq_Sort)(nil),     // 4: configimage.ListConfigReq.Sort
	(*ListConfigReq_Selector)(nil), // 5: configimage.ListConfigReq.Selector
	(*common.KVConfig)(nil),        // 6: common.KVConfig
}
var file_configimage_proto_depIdxs = []int32{
	4, // 0: configimage.ListConfigReq.sorts:type_name -> configimage.ListConfigReq.Sort
	5, // 1: configimage.ListConfigReq.selectors:type_name -> configimage.ListConfigReq.Selector
	6, // 2: configimage.GetKeyValueResp.config:type_name -> common.KVConfig
	0, // 3: configimage.ConfigImage.ListConfig:input_type -> configimage.ListConfigReq
	2, // 4: configimage.ConfigImage.GetKeyValue:input_type -> configimage.GetKeyValueReq
	1, // 5: configimage.ConfigImage.ListConfig:output_type -> configimage.ListConfigResp
	3, // 6: configimage.ConfigImage.GetKeyValue:output_type -> configimage.GetKeyValueResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_configimage_proto_init() }
func file_configimage_proto_init() {
	if File_configimage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configimage_proto_rawDesc), len(file_configimage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configimage_proto_goTypes,
		DependencyIndexes: file_configimage_proto_depIdxs,
		MessageInfos:      file_configimage_proto_msgTypes,
	}.Build()
	File_configimage_proto = out.File
	file_configimage_proto_goTypes = nil
	file_configimage_proto_depIdxs = nil
}
