// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: configimage.proto

package configimage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigImage_ListConfig_FullMethodName  = "/configimage.ConfigImage/ListConfig"
	ConfigImage_GetKeyValue_FullMethodName = "/configimage.ConfigImage/GetKeyValue"
)

// ConfigImageClient is the client API for ConfigImage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigImageClient interface {
	// 获取配置集合
	ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error)
	// 获取键值配置
	GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error)
}

type configImageClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigImageClient(cc grpc.ClientConnInterface) ConfigImageClient {
	return &configImageClient{cc}
}

func (c *configImageClient) ListConfig(ctx context.Context, in *ListConfigReq, opts ...grpc.CallOption) (*ListConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigResp)
	err := c.cc.Invoke(ctx, ConfigImage_ListConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configImageClient) GetKeyValue(ctx context.Context, in *GetKeyValueReq, opts ...grpc.CallOption) (*GetKeyValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyValueResp)
	err := c.cc.Invoke(ctx, ConfigImage_GetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigImageServer is the server API for ConfigImage service.
// All implementations must embed UnimplementedConfigImageServer
// for forward compatibility.
type ConfigImageServer interface {
	// 获取配置集合
	ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error)
	// 获取键值配置
	GetKeyValue(context.Context, *GetKeyValueReq) (*GetKeyValueResp, error)
	mustEmbedUnimplementedConfigImageServer()
}

// UnimplementedConfigImageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigImageServer struct{}

func (UnimplementedConfigImageServer) ListConfig(context.Context, *ListConfigReq) (*ListConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfig not implemented")
}
func (UnimplementedConfigImageServer) GetKeyValue(context.Context, *GetKeyValueReq) (*GetKeyValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (UnimplementedConfigImageServer) mustEmbedUnimplementedConfigImageServer() {}
func (UnimplementedConfigImageServer) testEmbeddedByValue()                     {}

// UnsafeConfigImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigImageServer will
// result in compilation errors.
type UnsafeConfigImageServer interface {
	mustEmbedUnimplementedConfigImageServer()
}

func RegisterConfigImageServer(s grpc.ServiceRegistrar, srv ConfigImageServer) {
	// If the following call pancis, it indicates UnimplementedConfigImageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigImage_ServiceDesc, srv)
}

func _ConfigImage_ListConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigImageServer).ListConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigImage_ListConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigImageServer).ListConfig(ctx, req.(*ListConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigImage_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigImageServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigImage_GetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigImageServer).GetKeyValue(ctx, req.(*GetKeyValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigImage_ServiceDesc is the grpc.ServiceDesc for ConfigImage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigImage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configimage.ConfigImage",
	HandlerType: (*ConfigImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConfig",
			Handler:    _ConfigImage_ListConfig_Handler,
		},
		{
			MethodName: "GetKeyValue",
			Handler:    _ConfigImage_GetKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configimage.proto",
}
