// Code generated by protoc-gen-easymicro-jsonschema. DO NOT EDIT.
package main

import (
	"fmt"
	"log"

	"github.com/995933447/mconfigcenter/common"
	"github.com/995933447/runtimeutil"
	"github.com/invopop/jsonschema"
	jsoniter "github.com/json-iterator/go"
)

func main() {
	schema := Output()
	s, err := jsoniter.MarshalToString(schema)
	if err != nil {
		log.Fatal(runtimeutil.NewStackErr(err))
	}
	fmt.Print(s)
}

func OutputFormatJsonString() (string, error) {
	b, err := OutputFormatJson()
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func OutputFormatJson() ([]byte, error) {
	schema := Output()
	return jsoniter.Marshal(schema)
}

func Output() *jsonschema.Schema {
	r := &jsonschema.Reflector{}
	r.DoNotReference = true
	r.AllowAdditionalProperties = true
	r.RequiredFromJSONSchemaTags = true
	r.FieldNameTag = "bson"
	return r.Reflect(&common.KVConfig{})
}
