// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/mconfigcenter/configimage"
	"github.com/995933447/mconfigcenter/configimageserver/handler"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(configimage.EasymicroGRPCPbServiceNameConfigImage, "ListConfig", handler.ConfigImageHandler.ListConfig, func() *configimage.ListConfigReq {
		return &configimage.ListConfigReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(configimage.EasymicroGRPCPbServiceNameConfigImage, "GetKeyValue", handler.ConfigImageHandler.GetKeyValue, func() *configimage.GetKeyValueReq {
		return &configimage.GetKeyValueReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
