// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/mconfigcenter/configimage"
	"github.com/995933447/mconfigcenter/configimageserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	configimage.EasymicroGRPCPbServiceNameConfigImage,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	configimage.RegisterConfigImageServer(server, handler.ConfigImageHandler)
	return nil
}
